### ISSUE TITLE
Suggestion: provide some documentation in autocompletion of keywords

### ISSUE THREAD

**Issue by Galad** [specsolutions/deveroom-visualstudio#3]
When using the autocompletion on an empty line (using CTRL + space), a list of available keywords and symbols such as Given, When, or ```, *, etc. is displayed.

It would be nice to have a tooltip explaining the purpose of each keyword / symbol.

**Comment by gasparnagy** [comment]
Good point! Thx!

**Comment by gasparnagy** [comment]
This is implemented. The new feature will be released soon.

**Comment by gasparnagy** [comment]
Released as v1.4.0
