### ISSUE TITLE
Show colours of Specflow table headings in black like with Specflow for Visual Studio

### ISSUE THREAD

**Issue by david-ttl** [specsolutions/deveroom-visualstudio#31]
When using Specflow for Visual Studio it shows the column headings in tables in black to distinguish them from the rows which are in red.
But in Deveroom the colourings are inconsistent (see below). Can they be made to be as they are in Specflow for Visual Studio?

Deveroom:
![deveroom](https://user-images.githubusercontent.com/50414069/57384456-90d78a80-71a8-11e9-91a5-0c0aa7e914bc.JPG)

Specflow for Visual Studio:
![specflow for vs](https://user-images.githubusercontent.com/50414069/57384467-9634d500-71a8-11e9-9e5f-f72025ec003f.JPG)

**Comment by gasparnagy** [comment]
Implementation notes: 
* Define a new TagType: `DataTableHeader` (see [`DeveroomTagTypes`](https://github.com/specsolutions/deveroom-visualstudio/blob/master/Deveroom.VisualStudio/Editor/Services/DeveroomTagTypes.cs))
* Extend scenario with `DataTableHeader` synxtax expectations [here](https://github.com/specsolutions/deveroom-visualstudio/blob/master/Tests/Deveroom.VisualStudio.Specs/Features/Editor/SyntaxColoring.feature#L264) (to expected multiple tag types, you need to list them in the step with commas, like [here](https://github.com/specsolutions/deveroom-visualstudio/blob/master/Tests/Deveroom.VisualStudio.Specs/Features/Editor/SyntaxColoring.feature#L208))
* Recognize data table header cells as `DataTableHeader` around [this line](https://github.com/specsolutions/deveroom-visualstudio/blob/master/Deveroom.VisualStudio/Editor/Services/DeveroomTagParser.cs#L119) (see [examples table](https://github.com/specsolutions/deveroom-visualstudio/blob/master/Deveroom.VisualStudio/Editor/Services/DeveroomTagParser.cs#L180) for as example)
* Define a classification (coloring) for the DataTableHeader in [`DeveroomClassifications`](https://github.com/specsolutions/deveroom-visualstudio/blob/master/Deveroom.VisualStudio/Editor/Classification/DeveroomClassifications.cs)
* Map the tag type to the classification [here](https://github.com/specsolutions/deveroom-visualstudio/blob/master/Deveroom.VisualStudio/Editor/Classification/DeveroomClassifier.cs#L12)

@david-ttl do you want to try?
