### ISSUE TITLE
Regenerate Feature.cs file comes back as error if there is a space in the file name

### ISSUE THREAD

**Issue by lauragilmour** [specsolutions/deveroom-visualstudio#34]
Regenerating all of the feature.cs file worked fine until I did it for projects that had a space in the name, and then it came back with the error 

﻿#error Error during generation. 
//Error: Illegal characters in path.

Is this something that deveroom is unable to support?

**Comment by gasparnagy** [comment]
@lauragilmour probably a bug. I will check.

**Comment by lewisreilly** [comment]
@gasparnagy the illegal character in the path came from the folder the project lived in having a space in it's name e.g. folder/application 2/app.csproj. 

Removing the space stopped the error from occurring.

**Comment by gasparnagy** [comment]
Fixed. The fix will be released in a few days.

**Comment by gasparnagy** [comment]
The fix has just been released as v1.3.0.
