### ISSUE TITLE
Devroom Integration with SpecFlow+ 

### ISSUE THREAD

**Issue by okyrylenko** [specsolutions/deveroom-visualstudio#42]
Hi, I am using Specflow+. When I install a devroom I got a warning that I have Specflow+ and Devroom installed and need to uninstall one in case to use the other one. Can I use both Speclow+ and Devroom?
Thank you

**Comment by gasparnagy** [comment]
@okyrylenko In short: SpecFlow+ components can be used with Deveroom!

The warning you have got was related to the "SpecFlow for VisualStudio" Visual Studio extension (this is what does the same job as Deveroom). This is not part of SpecFlow+.
SpecFlow+ consists of [several libraries and tools](https://specflow.org/plus/) that make test execution easier (the most commonly used is the SpecFlow+ Runner). As these components are not related to the Visual Studio directly (they are installed as NuGet packages), they can be used with Deveroom!

Does this answer your question?

**Comment by okyrylenko** [comment]
@gasparnagy thank you. That cleared things out

**Comment by okyrylenko** [comment]
it is a slightly different question but could be related to the original topic. I do not see deveroom features. I have specflow+ installed. My guess is that somehow that interfere with a usage of a deveroom. I choose Feature File For SpecFlow option when I create a new file which indicates that deveroom installed. But when I start working in a feature file I do not see deveroom features. For example I do not see define steps option when trying to generate step definitions.  
![image](https://user-images.githubusercontent.com/40716729/60974925-fc4cee00-a2f8-11e9-9f95-70e3e469e2dc.png)

**Comment by gasparnagy** [comment]
It look like that you also have the "SpecFlow for Visual Studio" extension also installed (Deveroom uses an coral color for undefined steps, the "SpecFlow for Visual Studio" extension uses the purple I see on your screenshot.) Disable or uninstall the "SpecFlow for Visual Studio" extension, and restart Visual Studio and then hopefully you will see the Deveroom features.
