### ISSUE TITLE
annoying warning with specflow 3 

### ISSUE THREAD

**Issue by Ninelya** [specsolutions/deveroom-visualstudio#44]
Hi)
Thanks for your product, love it!

I'm using SpecFlow 3.0.225 and VS 2019, and my problem is that I get these popup warnings every time I save edited feature file:
'Warning: ShowProblem: User Notification: Unable to find SpecFlow tools folder: 'C:\Users\{username}\.nuget\packages\specflow\3.0.225\tools'. Build solution to ensure that all packages are restored. The feature file has to be re-generated (e.g. by saving) after the packages have been restored.'
Thing is SpecFlow 3 doesn't have tools folder, its content was moved to separate package SpecFlow.Tools.MsBuild.Generation.
I'm kinda tired of these popups, how can I suppress them at least? Cause everything else works fine :slightly_smiling_face:

**Comment by gasparnagy** [comment]
Thx for the feedback. 

Whether the design-time generation (the generation triggered by saving the file in the editor) is enabled by the "SpecFlowSingleFileGenerator" value in the custom tool setting of the feature files. If you have migrated the project from SpecFlow v2, this value is still set for your feature files and this is why Deveroom tries finding the tools folder. The solution would be to remove this setting from all of your feature files as it is described here: https://specflow.org/documentation/Generate-Tests-from-MsBuild/

For the newly added feature files, Deveroom will detect the SpecFlow version and will not set the "SpecFlowSingleFileGenerator" custom tool setting, so this is a one-time fix.

Unfortunately the Visual Studio technology we use, does not allow skipping the generation based on the SpecFlow version (we could display a better error message though). But Deveroom could automatically detect this situation and suggest/help with removing the "SpecFlowSingleFileGenerator" custom tool setting. I will think on that.

**Comment by Ninelya** [comment]
Indeed, I have migrated my project from SpecFlow v2, and copied .feature files ever since :)
Cleaning .csproj from all the trash helped.
Thank you for such fast reply :)
