### ISSUE TITLE
Getting "The type initializer 'Equ.MemberwiseEquatable'1' threw an exception" exception when creating feature file for Specflow

### ISSUE THREAD

**Issue by okyrylenko** [specsolutions/deveroom-visualstudio#45]
Getting "The type initializer 'Equ.MemberwiseEquatable'1' threw an exception" exception when creating feature file for Specflow

Steps:
Click new Item
Select Feature File For Specflow file type
type calculator.feature
Click add

Expected a new feature file is created
Actual getting an exception

Note: 

- Deveroom Version 1.4.0
- I am able to create a feature file using specflow but deveroom. I tried to uninstall and install back 

- deveroom extensions but still failing

**Comment by gasparnagy** [comment]
Strange. I could not reproduce it, but released a hotfix: 1.4.1, where I have removed the `Equ` library (and reverted to "manual" equality).
The release should be ready in a few minuted on marketplace

**Comment by okyrylenko** [comment]
The bug is gone now. Thank you
