### ISSUE TITLE
Binding scope not used while searching for step definitions

### ISSUE THREAD

**Issue by kstudnik** [specsolutions/deveroom-visualstudio#52]
Using Deveroom 1.4.2
Steps to reproduce:
In feature file `Issue.feature`, I have step named (example) `When I add sth new`
Also in another feature file `Bind.feature`, I have step with the same name.

But the implementations of steps differ, are placed in separate classes and are distinguished using Scope
[Binding, Scope(Feature = "Issue")]

I was expecting that Deveroom solves that properly, but instead, I got an error message that there are ambiguous step definitions
![image](https://user-images.githubusercontent.com/912304/65413776-7538ed80-ddf2-11e9-8e70-f85c35959456.png)

**Comment by gasparnagy** [comment]
@kstudnik we currently have tag scoping implemented so far. Would you be interested to help with implementing feature scoping? (Should not be that hard having tag scopes implemented.)

**Comment by kstudnik** [comment]
I must admit, I have never contributed to github projects. But it may be a good opportunity to start. 
I can not promise miracles, but I'll look into it.

**Comment by gasparnagy** [comment]
@kstudnik I am happy to help. Once you will get the solution compiling, you can start making the first step (for me that would be adding a scenario to describe the behavior, like the "Matches scoped step definitions" scenario in `Editor\StepAnalysis.feature`). Once you have that, you can make a Pull Request (if you prefix the PR name with "WIP", it will be visible that this is not yet ready). I keep review the progress there and give hits about the next steps.

**Comment by gasparnagy** [comment]
Fixed by #55, thx to @scasteran. (I will do a release later this week.)
