### ISSUE TITLE
Exit code: 4 with SpecFlow 3.1.62

### ISSUE THREAD

**Issue by AnnieOletubo** [specsolutions/deveroom-visualstudio#56]
Hi all,

I have an error on my solution since I update it to work with SpecFlow (3.1.62) / SpecFlow.Tools.MsBuild.Generation (3.1.62)  / SpecRun.Runner (3.1.33) and SpecRun.SpecFlow.3-1-0 (3.1.33).
I have a specflow.json in my project 
{
  "bindingCulture": {
    "language": "en-us"
  },
  "language": {
    "feature": "en-us"
  },
  "plugins": [],
  "stepAssemblies": [
    { "assembly": "Hiptest.Tools" },
    { "assembly": "Common" },
    { "assembly": "Features" },
    { "assembly": "DEdge.Common" },
    { "assembly": "DEdge.Extranet" },
    { "assembly": "DEdge.Mobile" },
    { "assembly": "DEdge.BookingEngine" },
    { "assembly": "DEdge.Connectivity" },
    { "assembly": "Availpro.BackOffice" },
    { "assembly": "Availpro.HotelRegistration" },
    { "assembly": "Availpro.Common" },
    { "assembly": "Availpro.Extranet" },
    { "assembly": "Availpro.BookingEngine" },
    { "assembly": "Availpro.Pms" },
    { "assembly": "Fastbooking.Common" },
    { "assembly": "Fastbooking.OpenId" },
    { "assembly": "Fastbooking.Api" },
    { "assembly": "Fastbooking.BackOffice" },
    { "assembly": "Fastbooking.Attraction" },
    { "assembly": "Fastbooking.AdminV2" },
    { "assembly": "ExternalApplications" }
  ]
}

When I build my solution, Deveroom failed with an Exit code :4:

Info: CheckConfiguration: Configuration changed
Warning: InvokeDiscovery: Error during binding discovery. 
Command executed:
  C:\Projects\GitProjects\dedge.test.solution\Features\bin\Debug\net472> C:\USERS\AOLETUBO\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_F2157D07\EXTENSIONS\0K4F05FM.S0A\Connectors\V1\deveroom-specflow-v1.exe discovery C:\Projects\GitProjects\dedge.test.solution\Features\bin\Debug\net472\Features.dll C:\Projects\GitProjects\dedge.test.solution\Features\specflow.json
Exit code: 4
Message: 
Error: Une exception a été levée par la cible d'un appel. -> Échec de l'initialisation du système de configuration -> Données non valides au niveau racine. Ligne 1, position 1. (C:\Projects\GitProjects\dedge.test.solution\Features\specflow.json line 1) -> Données non valides au niveau racine. Ligne 1, position 1.
Exception: System.Reflection.TargetInvocationException->System.Configuration.ConfigurationErrorsException->System.Configuration.ConfigurationErrorsException->System.Xml.XmlException
StackTrace:
   à System.Xml.XmlTextReaderImpl.Throw(Exception e)
   à System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   à System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   à System.Configuration.XmlUtil..ctor(Stream stream, String name, Boolean readToFirstElement, ConfigurationSchemaErrors schemaErrors)
   à System.Configuration.BaseConfigurationRecord.InitConfigFromFile()
   à System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   à System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   à System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
   à System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
   à System.Configuration.ClientConfigurationSystem.PrepareClientConfigSystem(String sectionName)
   à System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(String sectionName)
   à System.Configuration.ConfigurationManager.GetSection(String sectionName)
   à System.Configuration.PrivilegedConfigurationManager.GetSection(String sectionName)
   à System.Diagnostics.DiagnosticsConfiguration.GetConfigSection()
   à System.Diagnostics.DiagnosticsConfiguration.Initialize()
   à System.Diagnostics.DiagnosticsConfiguration.get_Sources()
   à System.Diagnostics.TraceSource.Initialize()
   à System.Net.Logging.InitializeLogging()
   à System.Net.Logging.get_On()
   à System.Net.Http.HttpMessageHandler..ctor()
   à System.Net.Http.HttpClientHandler..ctor()
   à TechTalk.SpecFlow.Analytics.HttpClientWrapper..ctor()

Server stack trace: 
   à System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   à System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   à BoDi.ObjectContainer.CreateObject(Type type, ResolutionList resolutionPath, RegistrationKey keyToResolve)
   à BoDi.ObjectContainer.TypeRegistration.Resolve(ObjectContainer container, RegistrationKey keyToResolve, ResolutionList resolutionPath)
   à BoDi.ObjectContainer.ResolveObject(RegistrationKey keyToResolve, ResolutionList resolutionPath)
   à BoDi.ObjectContainer.Resolve(Type typeToResolve, ResolutionList resolutionPath, String name)
   à System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   à System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   à System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   à BoDi.ObjectContainer.CreateObject(Type type, ResolutionList resolutionPath, RegistrationKey keyToResolve)
   à BoDi.ObjectContainer.TypeRegistration.Resolve(ObjectContainer container, RegistrationKey keyToResolve, ResolutionList resolutionPath)
   à BoDi.ObjectContainer.ResolveObject(RegistrationKey keyToResolve, ResolutionList resolutionPath)
   à BoDi.ObjectContainer.Resolve(Type typeToResolve, ResolutionList resolutionPath, String name)
   à System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   à System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   à System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   à BoDi.ObjectContainer.CreateObject(Type type, ResolutionList resolutionPath, RegistrationKey keyToResolve)
   à BoDi.ObjectContainer.TypeRegistration.Resolve(ObjectContainer container, RegistrationKey keyToResolve, ResolutionList resolutionPath)
   à BoDi.ObjectContainer.ResolveObject(RegistrationKey keyToResolve, ResolutionList resolutionPath)
   à BoDi.ObjectContainer.Resolve(Type typeToResolve, ResolutionList resolutionPath, String name)
   à System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   à System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   à System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   à BoDi.ObjectContainer.CreateObject(Type type, ResolutionList resolutionPath, RegistrationKey keyToResolve)
   à BoDi.ObjectContainer.TypeRegistration.Resolve(ObjectContainer container, RegistrationKey keyToResolve, ResolutionList resolutionPath)
   à BoDi.ObjectContainer.ResolveObject(RegistrationKey keyToResolve, ResolutionList resolutionPath)
   à BoDi.ObjectContainer.Resolve(Type typeToResolve, ResolutionList resolutionPath, String name)
   à System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   à System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   à System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   à BoDi.ObjectContainer.CreateObject(Type type, ResolutionList resolutionPath, RegistrationKey keyToResolve)
   à BoDi.ObjectContainer.TypeRegistration.Resolve(ObjectContainer container, RegistrationKey keyToResolve, ResolutionList resolutionPath)
   à BoDi.ObjectContainer.ResolveObject(RegistrationKey keyToResolve, ResolutionList resolutionPath)
   à BoDi.ObjectContainer.Resolve(Type typeToResolve, ResolutionList resolutionPath, String name)
   à BoDi.ObjectContainer.Resolve[T](String name)
   à TechTalk.SpecFlow.TestRunnerManager.CreateTestRunner(Int32 threadId)
   à Deveroom.VisualStudio.SpecFlowConnector.Discovery.V30.SpecFlowV30P220Discoverer.GetBindingRegistry(Assembly testAssembly, String configFilePath)
   à Deveroom.VisualStudio.SpecFlowConnector.Discovery.BaseDiscoverer.DiscoverInternal(Assembly testAssembly, String testAssemblyPath, String configFilePath)
   à Deveroom.VisualStudio.SpecFlowConnector.Discovery.RemotingBaseDiscoverer.Discover(String testAssemblyPath, String configFilePath)
   à System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   à System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   à System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   à System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   à Deveroom.VisualStudio.SpecFlowConnector.Discovery.IRemotingSpecFlowDiscoverer.Discover(String testAssembly, String configFilePath)
   à Deveroom.VisualStudio.SpecFlowConnector.Discovery.DiscoveryProcessor.Process()
   à Deveroom.VisualStudio.SpecFlowConnector.ConsoleRunner.EntryPoint(String[] args)

Warning: InvokeDiscovery: The project bindings (e.g. step definitions) could not be discovered. Navigation, step completion and other features are disabled. 
  Please check the error message above and report to https://github.com/specsolutions/deveroom-visualstudio/issues if you cannot fix.

I didn't change my specflow.json for the upgrade.. so I don't understand what is going wrong with it.

Anyone as an idea of how I can correct it?

Thanks

(I tried to remove and put back the Deveroom extension)

For your information, there is an issue with SpecFlow 3.1.62 and Cucumber.Messages 7.0. You must use Cucumber.Messages 6.0 (see Andreas' comment : https://groups.google.com/d/msg/specflow/BYwfKbob9dw/qjraFzoDBAAJ )

**Comment by gasparnagy** [comment]
Could you please zip the specflow.json config file and attach to this issue. (Zipping is important because it might preserve some Unicode prexfix characters that might be relevant.)

**Comment by AnnieOletubo** [comment]
[specflow.zip](https://github.com/specsolutions/deveroom-visualstudio/files/3879740/specflow.zip)
here is the zip

**Comment by gasparnagy** [comment]
The issue was related to using `specflow.json` config file on a .NET Framework project. This has been fixed now. I try to make a release later today.

**Comment by AnnieOletubo** [comment]
Thanks a lot! :)
