### ISSUE TITLE
Visual Studio warning: The project bindings could not be discovered

### ISSUE THREAD

**Issue by daveh551** [specsolutions/deveroom-visualstudio#69]
Something has apparently changed recently.  After working with a SpecFlow project for several months, I'm suddenly getting a warning message "The project bindings (e.g. step definitions) could not be discovered.  Navigation, step completion, and other features are disabled".

There is no error code or other information given.

Configuration: Visual Studio 2019 (v. 16.8.3)

DevERoom extension.

Windows 10

**Comment by rsloggett-prmaconsulting** [comment]
I too am seeing this - is this a .NET Framework 5 issue (my project is TargetFramework net5.0)?

**Comment by daveh551** [comment]
Mine is a .NetCore 3.1 app.

**Comment by daveh551** [comment]
On one or two runs, I did get some more information back:  There's a missing method exception for BoDi.ObjectContainer.RegisterTypeAs(System.String).
It looks like it's thrown at DevERoom.VisualStudio.SpecFlowConnector.Discovery.V31.SpecFlowV31Discoverer.DependencyProvider.RegisterGloblConainterDefaults.

Hope that helps.

**Comment by gasparnagy** [comment]
@daveh551 Could you please let me know the exact SpecFlow version you use? Is it v3.7?

**Comment by gasparnagy** [comment]
I have reproduced the issue and made the fix. Waiting for the CI build to pass and then I will release it out.

**Comment by gasparnagy** [comment]
Fixed and released now. v1.6.2 will be available soon for manual/automatic update.

**Comment by rick3500** [comment]
This is my first attempt to build specflow using the 'Xamarin.UITest Cross-Platform Test Project' template and I am getting "The project bindings (e.g. step definitions) could not be discovered. Navigation, step completion and other features are disabled" message 

It is actually a Warning and not an error.

Template used to initialize the project 'Xamarin.UITest Cross-Platform Test Project' w/FluidAssertions (6.2.0)
Microsoft.NET.Test.Sdk (17.0.0)
NUnit (3.13.2)
NUnit3TestAdapter (4.1.0)
Specflow.NUnit (3.9.40)
Specflow.Plus.LivingDocPlugin (3.9.57)
Visual Studio 2022 (64-bit) Current (Version 17.0.0
Xamarin - 17.0.0.336 (d17-0@29731f2)
Xamarin Designer - 17.0.0.182 (remotes/origin/d17-0@204898d)
Xamarin Templates - 17.0.17 (ie977b0)
Xamarin.Android.SDK - 12.1.0.5 (d17-0/6b0e6b2)
Xamarin.iOS and Xamarin.Mac SDK 15.0.0.18 (577ff6329)

**Comment by gasparnagy** [comment]
@rick3500 Do you see any detailed error message? Maybe in the log file (in `C:\Users\<your-user>\AppData\Local\Deveroom` folder). Could you maybe also try with VS2020 using the SpecFlow for Visual Studio 2022 extension (a successor of Deveroom)?

**Comment by LJGitHubby** [comment]
C:\Program Files\dotnet\dotnet.exe exec
