### ISSUE TITLE
Support for Visual Studio 2022

### ISSUE THREAD

**Issue by kaladinstorm84** [specsolutions/deveroom-visualstudio#74]
Currently cannot install Deveroom in Visual Studio 2022 as it doesnt appear in the extension gallery. Is there any plan to release for the latest version of 2022

**Comment by gasparnagy** [comment]
@kaladinstorm84 The new official "SpecFlow for Visual Studio" extension for VS2022 is based on Deveroom, so install that extension in VS2022 for the deveroom-experience. The new codebase (a fork of Deveroom) is here: https://github.com/SpecFlowOSS/SpecFlow.VS.

**Comment by kaladinstorm84** [comment]
Could the Wiki / Supported Versions page be updated to reflect this?
